# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5769f92fe5ed5b7a470b7735e2d2ea15710a19a02a58f8d6824cd189cb12f70315d394bd8fa4c9f293ac31b3b7cfff51cbe1a00ebfee4b4c2b3024438d3583

test:
  secret_key_base: 51c158bb8c07fed9e5d41e066186aa2e5e3c209b42f343178a50511942c6d86831a2a293db0bc574c66c57cad2c5108de4d7e3de4733c068dc1162dbfe4e06fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
